class Serving:
    def __init__(self, body):
        self.id = body.get('serving_id')
        self.description = body.get('serving_description')
        self.metric_serving_amount = body.get('metric_serving_amount')
        self.metric_serving_unit = body.get('metric_serving_unit')
        self.number_of_units = body.get('number_of_units')
        self.calories = float(body.get('calories'))
        self.carbohydrate = float(body.get('carbohydrate'))
        self.protein = float(body.get('protein'))
        self.fat = float(body.get('fat'))
        self.cholesterol = float(body.get('cholesterol'))
        self.sodium = float(body.get('sodium'))
        self.fiber = float(body.get('fiber'))
        self.sugar = float(body.get('sugar'))