"""add unique constraint to custom_food name

Revision ID: ebcc582cd1df
Revises: f16a416bf582
Create Date: 2026-05-24 15:54:41.352866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebcc582cd1df'
down_revision = 'f16a416bf582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_food', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_custom_food_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_food', schema=None) as batch_op:
        batch_op.drop_constraint('uq_custom_food_name', type_='unique')

    # ### end Alembic commands ###
