"""add custom_food table and update ingredient nullable fields

Revision ID: f16a416bf582
Revises: fa557cd67577
Create Date: 2026-05-24 15:49:25.149081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16a416bf582'
down_revision = 'fa557cd67577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_food',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('serving_description', sa.String(), nullable=False),
        sa.Column('calories', sa.Float(), nullable=False),
        sa.Column('fat', sa.Float(), nullable=False),
        sa.Column('sodium', sa.Float(), nullable=False),
        sa.Column('carbohydrate', sa.Float(), nullable=False),
        sa.Column('fiber', sa.Float(), nullable=False),
        sa.Column('protein', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_food_id', sa.Integer(), nullable=True))
        batch_op.alter_column('food_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('serving_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_ingredients_custom_food_id', 'custom_food', ['custom_food_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ingredients_custom_food_id', type_='foreignkey')
        batch_op.alter_column('serving_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('food_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('custom_food_id')

    op.drop_table('custom_food')
    # ### end Alembic commands ###
